# Architecture
arch: ResNet34_1w1a

# ===== Dataset ===== #
data: ./dataset
set: ImageNet
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
no_bn_decay: True
warmup_length: 0

# ===== Network training config ===== #
epochs: 200
weight_decay: 0.0001
momentum: 0.9
batch_size: 512
label_smoothing: 0.0
num_classes: 1000
trainers: ovsw

# ===== Binary Neural Network ===== #
conv_type: OvSWConv2d
bn_type: BatchNorm2d
init: kaiming_normal
mode: fan_in
forward_type: xnor
nonlinearity: hardtanh
act_a: binary
act_w: ste

# ===== Hardware setup ===== #
workers: 16